# Generated by Django 5.0 on 2024-12-05 12:11

import django.core.validators
import django.db.models.deletion
import payments.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0017_alter_booking_options_booking_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000000)], verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('REFUNDED', 'refunded')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_type', models.CharField(choices=[('ONLINE', 'online'), ('CASH', 'cash'), ('CARD', 'card')], default='online', max_length=20, verbose_name='نوع پرداخت')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی پی'), ('nextpay', 'نکست پی')], default='zarinpal', max_length=20, verbose_name='درگاه پرداخت')),
                ('tracking_code', models.CharField(max_length=200, unique=True, validators=[payments.validators.TrackingCodeValidator()], verbose_name='کد پیگیری')),
                ('reference_id', models.CharField(blank=True, max_length=200, validators=[payments.validators.ReferenceIdValidator()], verbose_name='شناسه مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.booking', verbose_name='رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='دلیل درخواست')),
                ('bank_account', models.CharField(max_length=26, validators=[payments.validators.BankAccountValidator()], verbose_name='شماره حساب')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'درخواست استرداد',
                'verbose_name_plural': 'درخواست\u200cهای استرداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('REFUNDED', 'refunded')], max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(max_length=200, validators=[payments.validators.TrackingCodeValidator()], verbose_name='کد پیگیری')),
                ('bank_reference_id', models.CharField(blank=True, max_length=200, verbose_name='شناسه مرجع بانکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
