# Generated by Django 5.1.4 on 2024-12-14 12:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.05')), django.core.validators.MaxValueValidator(Decimal('0.20'))], verbose_name='نرخ کمیسیون')),
                ('commission_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کمیسیون')),
                ('owner_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='سهم مالک')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('settlement_status', models.CharField(choices=[('pending', 'در انتظار تسویه'), ('processing', 'در حال تسویه'), ('completed', 'تسویه شده'), ('failed', 'تسویه ناموفق')], default='pending', max_length=20, verbose_name='وضعیت تسویه')),
                ('check_in_date', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out_date', models.DateField(verbose_name='تاریخ خروج')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('settlement_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('tracking_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='کد پیگیری')),
                ('payment_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت')),
                ('settlement_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تسویه')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.property', verbose_name='ملک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='?????')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.03, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='نرخ کمیسیون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_properties', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='مبلغ درخواستی')),
                ('reason', models.TextField(verbose_name='دلیل استرداد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('refunded', 'مسترد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('bank_account', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('admin_note', models.TextField(blank=True, verbose_name='توضیحات ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payments.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست استرداد',
                'verbose_name_plural': 'درخواست\u200cهای استرداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تسویه'), ('processing', 'در حال تسویه'), ('completed', 'تسویه شده'), ('failed', 'تسویه ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(max_length=50, null=True, unique=True, verbose_name='کد پیگیری')),
                ('bank_tracking_code', models.CharField(max_length=100, null=True, verbose_name='کد پیگیری بانک')),
                ('bank_reference_id', models.CharField(max_length=100, null=True, verbose_name='شناسه مرجع بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('settled_at', models.DateTimeField(null=True, verbose_name='تاریخ تسویه')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'تسویه حساب',
                'verbose_name_plural': 'تسویه حساب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('payment', 'پرداخت'), ('refund', 'استرداد'), ('settlement', 'تسویه')], max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(max_length=50, unique=True, verbose_name='کد پیگیری')),
                ('bank_tracking_code', models.CharField(max_length=100, null=True, verbose_name='کد پیگیری بانک')),
                ('bank_reference_id', models.CharField(max_length=100, null=True, verbose_name='شناسه مرجع بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
