# Generated by Django 5.1.4 on 2024-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='???')),
                ('email', models.EmailField(max_length=254, verbose_name='?????')),
                ('subject', models.CharField(max_length=200, verbose_name='?????')),
                ('message', models.TextField(verbose_name='????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ?????')),
                ('is_read', models.BooleanField(default=False, verbose_name='?????? ???')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '???????',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='????')),
                ('answer', models.TextField(verbose_name='????')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='?????')),
                ('is_active', models.BooleanField(default=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '???? ??????',
                'verbose_name_plural': '?????? ??????',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '?'), (2, '??'), (3, '???'), (4, '????'), (5, '?????')], verbose_name='??????')),
                ('comment', models.TextField(verbose_name='???')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ???')),
                ('is_approved', models.BooleanField(default=False, verbose_name='????? ???')),
            ],
            options={
                'verbose_name': '???????',
                'verbose_name_plural': '?????????',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='?????')),
                ('is_active', models.BooleanField(default=True, verbose_name='????')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ?????')),
            ],
            options={
                'verbose_name': '???????',
                'verbose_name_plural': '??????????',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='?????')),
                ('message', models.TextField(verbose_name='????')),
                ('notification_type', models.CharField(choices=[('info', '???????????'), ('success', '??????'), ('warning', '?????'), ('error', '???')], default='info', max_length=10, verbose_name='???')),
                ('is_read', models.BooleanField(default=False, verbose_name='?????? ???')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ?????')),
            ],
            options={
                'verbose_name': '?????',
                'verbose_name_plural': '????????',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='?????')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='?????')),
                ('content', models.TextField(verbose_name='?????')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='?????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ?????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????? ?????????')),
                ('is_active', models.BooleanField(default=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '???',
                'verbose_name_plural': '??????',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='??? ????')),
                ('site_description', models.TextField(verbose_name='??????? ????')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='????? ????')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='???? ????')),
                ('address', models.TextField(verbose_name='????')),
                ('instagram', models.URLField(blank=True, verbose_name='??????????')),
                ('telegram', models.URLField(blank=True, verbose_name='??????')),
                ('whatsapp', models.URLField(blank=True, verbose_name='??????')),
                ('about_us', models.TextField(verbose_name='?????? ??')),
                ('terms', models.TextField(verbose_name='?????? ? ??????')),
                ('privacy', models.TextField(verbose_name='???? ?????')),
            ],
            options={
                'verbose_name': '??????? ????',
                'verbose_name_plural': '??????? ????',
            },
        ),
    ]
