# Generated by Django 5.1.3 on 2024-11-29 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('house', 'خانه'), ('commercial', 'تجاری')], max_length=20, verbose_name='نوع ملک')),
                ('area', models.IntegerField(verbose_name='متراژ')),
                ('rooms', models.IntegerField(verbose_name='تعداد اتاق')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('images', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصاویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ ودیعه')),
                ('rent', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ اجاره ماهیانه')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'ملک اجاره\u200cای',
                'verbose_name_plural': 'املاک اجاره\u200cای',
            },
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('house', 'خانه'), ('commercial', 'تجاری')], max_length=20, verbose_name='نوع ملک')),
                ('area', models.IntegerField(verbose_name='متراژ')),
                ('rooms', models.IntegerField(verbose_name='تعداد اتاق')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('images', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصاویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت فروش')),
                ('price_per_meter', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت هر متر')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'ملک فروشی',
                'verbose_name_plural': 'املاک فروشی',
            },
        ),
    ]
