# Generated by Django 5.1.4 on 2024-12-19 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='min_stay',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='document_type',
        ),
        migrations.AddField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('daily', 'اجاره روزانه')], default='rent', max_length=10, verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='property',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.propertyfeature', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property', verbose_name='ملک'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(verbose_name='ساعت بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_visits', to=settings.AUTH_USER_MODEL, verbose_name='بازدیدکننده'),
        ),
    ]
