# Generated by Django 5.1.3 on 2024-11-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_rentproperty_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('visit_time', models.DateTimeField(verbose_name='زمان بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.saleproperty', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'درخواست بازدید',
                'verbose_name_plural': 'درخواست\u200cهای بازدید',
            },
        ),
    ]
