# Generated by Django 5.1.3 on 2024-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سرویس بهداشتی'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='building_area',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ بنا'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='construction_year',
            field=models.PositiveIntegerField(default=0, verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='document_type',
            field=models.CharField(choices=[('registered', 'سند ثبتی'), ('detailed', 'سند تفکیکی'), ('cooperative', 'سند تعاونی'), ('endowment', 'سند وقفی'), ('temporary', 'قولنامه\u200cای')], default='registered', max_length=50, verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='floor',
            field=models.PositiveIntegerField(default=0, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='land_area',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ زمین'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='total_floors',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کل طبقات'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سرویس بهداشتی'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='building_area',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ بنا'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='construction_year',
            field=models.PositiveIntegerField(default=0, verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='document_type',
            field=models.CharField(choices=[('registered', 'سند ثبتی'), ('detailed', 'سند تفکیکی'), ('cooperative', 'سند تعاونی'), ('endowment', 'سند وقفی'), ('temporary', 'قولنامه\u200cای')], default='registered', max_length=50, verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='floor',
            field=models.PositiveIntegerField(default=0, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='land_area',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ زمین'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='total_floors',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کل طبقات'),
        ),
    ]
