# Generated by Django 5.1.4 on 2024-12-23 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_address_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrentproperty',
            name='min_stay',
            field=models.PositiveIntegerField(default=1, help_text='حداقل تعداد شب\u200cهای اقامت', validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداقل مدت اقامت'),
        ),
    ]
