# Generated by Django 5.1.3 on 2024-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rentproperty_bathrooms_rentproperty_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='بالکن/تراس'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='cooling_system',
            field=models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='split', max_length=50, verbose_name='سیستم سرمایش'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='heating_system',
            field=models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='heater', max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='storage',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='بالکن/تراس'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='cooling_system',
            field=models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='split', max_length=50, verbose_name='سیستم سرمایش'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='heating_system',
            field=models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='heater', max_length=50, verbose_name='سیستم گرمایش'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='storage',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
    ]
