# Generated by Django 5.1.4 on 2024-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_dailyrentproperty_min_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='minimum_days',
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='has_transfer_fee',
            field=models.BooleanField(default=True, verbose_name='کمیسیون دارد'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='اجاره ماهیانه'),
        ),
    ]
