# Generated by Django 5.1.3 on 2024-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rentproperty_balcony_rentproperty_cooling_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='bus_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اتوبوس'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='district',
            field=models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه'), ('ferdowsi', 'شهرک فردوسی'), ('shahnameh', 'شهرک شاهنامه')], default='1', max_length=20, verbose_name='منطقه'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='metro_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مترو'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='محله'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='school_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مدارس'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='shopping_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مراکز خرید'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='bus_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اتوبوس'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='district',
            field=models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه'), ('ferdowsi', 'شهرک فردوسی'), ('shahnameh', 'شهرک شاهنامه')], default='1', max_length=20, verbose_name='منطقه'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='metro_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مترو'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='محله'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='school_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مدارس'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='shopping_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مراکز خرید'),
        ),
    ]
