# Generated by Django 5.1.3 on 2024-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rentproperty_bus_access_rentproperty_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='cabinet_type',
            field=models.CharField(choices=[('mdf', 'ام دی اف'), ('high_gloss', 'های گلاس'), ('wood', 'چوبی'), ('metal', 'فلزی')], default='mdf', max_length=50, verbose_name='نوع کابینت'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='facade_type',
            field=models.CharField(choices=[('stone', 'سنگ'), ('brick', 'آجر'), ('cement', 'سیمان'), ('composite', 'کامپوزیت'), ('glass', 'شیشه')], default='brick', max_length=50, verbose_name='نوع نما'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='flooring_type',
            field=models.CharField(choices=[('ceramic', 'سرامیک'), ('parquet', 'پارکت'), ('stone', 'سنگ'), ('mosaic', 'موزاییک'), ('laminate', 'لمینت')], default='ceramic', max_length=50, verbose_name='نوع کف\u200cپوش'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='security_system',
            field=models.BooleanField(default=False, verbose_name='سیستم امنیتی'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='cabinet_type',
            field=models.CharField(choices=[('mdf', 'ام دی اف'), ('high_gloss', 'های گلاس'), ('wood', 'چوبی'), ('metal', 'فلزی')], default='mdf', max_length=50, verbose_name='نوع کابینت'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='facade_type',
            field=models.CharField(choices=[('stone', 'سنگ'), ('brick', 'آجر'), ('cement', 'سیمان'), ('composite', 'کامپوزیت'), ('glass', 'شیشه')], default='brick', max_length=50, verbose_name='نوع نما'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='flooring_type',
            field=models.CharField(choices=[('ceramic', 'سرامیک'), ('parquet', 'پارکت'), ('stone', 'سنگ'), ('mosaic', 'موزاییک'), ('laminate', 'لمینت')], default='ceramic', max_length=50, verbose_name='نوع کف\u200cپوش'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='security_system',
            field=models.BooleanField(default=False, verbose_name='سیستم امنیتی'),
        ),
    ]
