# Generated by Django 5.1.3 on 2024-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rentproperty_cabinet_type_rentproperty_facade_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='building_direction',
            field=models.CharField(choices=[('north', 'شمالی'), ('south', 'جنوبی'), ('east', 'شرقی'), ('west', 'غربی'), ('north_south', 'شمالی-جنوبی'), ('east_west', 'شرقی-غربی')], default='north', max_length=20, verbose_name='جهت ساختمان'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='convertible',
            field=models.BooleanField(default=False, verbose_name='قابل تبدیل'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='exchangeable',
            field=models.BooleanField(default=False, verbose_name='قابل معاوضه'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='occupancy_status',
            field=models.CharField(choices=[('empty', 'خالی'), ('occupied_owner', 'در تصرف مالک'), ('occupied_tenant', 'در تصرف مستاجر')], default='empty', max_length=20, verbose_name='وضعیت سکونت'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='building_direction',
            field=models.CharField(choices=[('north', 'شمالی'), ('south', 'جنوبی'), ('east', 'شرقی'), ('west', 'غربی'), ('north_south', 'شمالی-جنوبی'), ('east_west', 'شرقی-غربی')], default='north', max_length=20, verbose_name='جهت ساختمان'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='convertible',
            field=models.BooleanField(default=False, verbose_name='قابل تبدیل'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='exchangeable',
            field=models.BooleanField(default=False, verbose_name='قابل معاوضه'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='occupancy_status',
            field=models.CharField(choices=[('empty', 'خالی'), ('occupied_owner', 'در تصرف مالک'), ('occupied_tenant', 'در تصرف مستاجر')], default='empty', max_length=20, verbose_name='وضعیت سکونت'),
        ),
    ]
