# Generated by Django 5.1.3 on 2024-11-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rentproperty_building_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentproperty',
            name='building_direction',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='convertible',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='exchangeable',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='facade_type',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='flooring_type',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='occupancy_status',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='security_system',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='building_direction',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='cabinet_type',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='convertible',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='exchangeable',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='facade_type',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='flooring_type',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='occupancy_status',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='security_system',
        ),
    ]
