# Generated by Django 5.1.4 on 2024-12-28 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_options_alter_property_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='district',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='district',
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default='نامشخص', max_length=100, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, default='نامشخص', help_text='آدرس کامل ملک را وارد کنید', null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
    ]
