# Generated by Django 5.1.3 on 2024-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_rentproperty_building_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.CharField(choices=[('morning', 'صبح (۹ تا ۱۲)'), ('afternoon', 'بعد از ظهر (۱۲ تا ۱۶)'), ('evening', 'عصر (۱۶ تا ۲۰)')], max_length=20, verbose_name='زمان بازدید'),
        ),
    ]
