# Generated by Django 5.1.3 on 2024-12-02 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_visit_visit_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('commercial', 'تجاری')], max_length=20, verbose_name='نوع ملک')),
                ('area', models.IntegerField(verbose_name='متراژ')),
                ('rooms', models.IntegerField(verbose_name='تعداد اتاق')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('images', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصاویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='تعداد اتاق خواب')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='تعداد سرویس بهداشتی')),
                ('land_area', models.PositiveIntegerField(default=0, verbose_name='متراژ زمین')),
                ('building_area', models.PositiveIntegerField(default=0, verbose_name='متراژ بنا')),
                ('construction_year', models.PositiveIntegerField(default=0, verbose_name='سال ساخت')),
                ('document_type', models.CharField(choices=[('registered', 'سند ثبتی'), ('detailed', 'سند تفکیکی'), ('cooperative', 'سند تعاونی'), ('endowment', 'سند وقفی'), ('temporary', 'قولنامه\u200cای')], default='registered', max_length=50, verbose_name='نوع سند')),
                ('floor', models.PositiveIntegerField(default=0, verbose_name='طبقه')),
                ('total_floors', models.PositiveIntegerField(default=0, verbose_name='تعداد کل طبقات')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('storage', models.BooleanField(default=False, verbose_name='انباری')),
                ('elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('balcony', models.BooleanField(default=False, verbose_name='بالکن/تراس')),
                ('heating_system', models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='heater', max_length=50, verbose_name='سیستم گرمایش')),
                ('cooling_system', models.CharField(choices=[('package', 'پکیج'), ('split', 'اسپلیت'), ('heater', 'بخاری'), ('fireplace', 'شومینه'), ('central', 'موتورخانه مرکزی')], default='split', max_length=50, verbose_name='سیستم سرمایش')),
                ('district', models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه'), ('ferdowsi', 'شهرک فردوسی'), ('shahnameh', 'شهرک شاهنامه')], default='1', max_length=20, verbose_name='منطقه')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='محله')),
                ('metro_access', models.BooleanField(default=False, verbose_name='دسترسی به مترو')),
                ('bus_access', models.BooleanField(default=False, verbose_name='دسترسی به اتوبوس')),
                ('shopping_access', models.BooleanField(default=False, verbose_name='دسترسی به مراکز خرید')),
                ('school_access', models.BooleanField(default=False, verbose_name='دسترسی به مدارس')),
                ('daily_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اجاره روزانه')),
                ('min_stay', models.IntegerField(default=1, verbose_name='حداقل مدت اقامت (روز)')),
                ('max_stay', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مدت اقامت (روز)')),
                ('max_guests', models.IntegerField(default=2, verbose_name='حداکثر تعداد مهمان')),
                ('wifi', models.BooleanField(default=False, verbose_name='اینترنت وای\u200cفای')),
                ('tv', models.BooleanField(default=False, verbose_name='تلویزیون')),
                ('kitchen', models.BooleanField(default=False, verbose_name='آشپزخانه مجهز')),
                ('washing_machine', models.BooleanField(default=False, verbose_name='ماشین لباسشویی')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'اقامتگاه روزانه',
                'verbose_name_plural': 'اقامتگاه\u200cهای روزانه',
            },
        ),
    ]
