# Generated by Django 5.1.3 on 2024-12-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_dailyrentproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='building_area',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='bus_access',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='construction_year',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='cooling_system',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='district',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='heating_system',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='metro_access',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='school_access',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='shopping_access',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='total_floors',
        ),
        migrations.AlterField(
            model_name='dailyrentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('room', 'اتاق خصوصی')], max_length=20, verbose_name='نوع اقامتگاه'),
        ),
    ]
