# Generated by Django 5.1.3 on 2024-12-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_dailyrentproperty_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا')], max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا')], max_length=20, verbose_name='نوع ملک'),
        ),
    ]
