# Generated by Django 5.1.3 on 2024-12-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_rentproperty_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrentproperty',
            name='latitude',
            field=models.FloatField(default=36.2972, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='dailyrentproperty',
            name='longitude',
            field=models.FloatField(default=59.6067, verbose_name='طول جغرافیایی'),
        ),
    ]
