# Generated by Django 5.1.3 on 2024-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_dailyrentproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='latitude',
            field=models.FloatField(default=36.2972, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='longitude',
            field=models.FloatField(default=59.6067, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='latitude',
            field=models.FloatField(default=36.2972, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='longitude',
            field=models.FloatField(default=59.6067, verbose_name='طول جغرافیایی'),
        ),
    ]
