# Generated by Django 5.0 on 2024-12-05 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0017_alter_booking_options_booking_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyavailability',
            options={'verbose_name': 'وضعیت رزرو', 'verbose_name_plural': 'وضعیت\u200cهای رزرو'},
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dailyrentproperty',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='building_area',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='bus_access',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='construction_year',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='cooling_system',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='heating_system',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='metro_access',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='school_access',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='shopping_access',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='building_area',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='bus_access',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='construction_year',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='cooling_system',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='heating_system',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='metro_access',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='school_access',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='shopping_access',
        ),
        migrations.RemoveField(
            model_name='saleproperty',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='property',
        ),
        migrations.AddField(
            model_name='dailyrentproperty',
            name='district',
            field=models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه')], default=1, max_length=20, verbose_name='منطقه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyrentproperty',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='dailyrentproperty',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='visit',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('saleproperty', 'rentproperty')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد مهمانان'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.dailyrentproperty', verbose_name='اقامتگاه'),
        ),
        migrations.AlterField(
            model_name='dailyrentproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='dailyrentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('room', 'اتاق خصوصی')], max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='dailyrentproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='propertyavailability',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.dailyrentproperty', verbose_name='اقامتگاه'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='deposit',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='ودیعه'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='district',
            field=models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه')], max_length=20, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='floor',
            field=models.IntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('room', 'اتاق خصوصی')], max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='اجاره ماهیانه'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='total_floors',
            field=models.IntegerField(verbose_name='تعداد کل طبقات'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='district',
            field=models.CharField(choices=[('1', 'منطقه ۱'), ('2', 'منطقه ۲'), ('3', 'منطقه ۳'), ('4', 'منطقه ۴'), ('5', 'منطقه ۵'), ('6', 'منطقه ۶'), ('7', 'منطقه ۷'), ('8', 'منطقه ۸'), ('9', 'منطقه ۹'), ('10', 'منطقه ۱۰'), ('11', 'منطقه ۱۱'), ('12', 'منطقه ۱۲'), ('13', 'منطقه ۱۳'), ('samen', 'منطقه ثامن'), ('shandiz', 'شاندیز'), ('torghabeh', 'طرقبه')], max_length=20, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='floor',
            field=models.IntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت هر متر'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('room', 'اتاق خصوصی')], max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='total_floors',
            field=models.IntegerField(verbose_name='تعداد کل طبقات'),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.CharField(choices=[('morning', 'صبح'), ('afternoon', 'بعد از ظهر'), ('evening', 'عصر')], max_length=20, verbose_name='زمان بازدید'),
        ),
    ]
