# Generated by Django 5.1.4 on 2024-12-12 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='??????')),
                ('object_id', models.IntegerField(null=True, verbose_name='????? ???')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='??????')),
                ('ip_address', models.GenericIPAddressField(verbose_name='???? IP')),
                ('user_agent', models.CharField(max_length=500, verbose_name='?????? ?????')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????? ??????',
                'verbose_name_plural': '????????? ??????',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=32, unique=True, verbose_name='?? ??????')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(50000)], verbose_name='????')),
                ('status', models.CharField(choices=[('pending', '?? ?????? ?????'), ('processing', '?? ??? ??????'), ('completed', '????? ???'), ('failed', '??????'), ('rejected', '?? ???'), ('cancelled', '??? ???')], default='pending', max_length=20, verbose_name='?????')),
                ('bank_account', models.CharField(max_length=26, verbose_name='????? ???')),
                ('bank_reference_id', models.CharField(blank=True, max_length=100, verbose_name='????? ?????? ?????')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='???? ?? ???????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ?????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????? ?????????')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='????? ?????')),
            ],
            options={
                'verbose_name': '????? ????',
                'verbose_name_plural': '????? ???????',
                'ordering': ['-created_at'],
            },
        ),
    ]
